version: '3.8'

services:
  # Gemini API Service
  gemini-rubric-api:
    build:
      context: .
      target: production
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with debugging tools
  gemini-rubric-api-dev:
    build:
      context: .
      target: dev
    ports:
      - "5002:5001"
      - "8888:8888"
    environment:
      - PORT=5001
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - dev

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gemini-rubric-api
    restart: unless-stopped
    profiles:
      - production

volumes:
  logs:
    driver: local
